version: 2

updates:
  - package-ecosystem: pip
    directory: /orchestrator
    target-branch: main
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /orchestrator
    target-branch: main
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
